name: diabetes-mlproject
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn==1.4.2
    - pandas==2.2.2
    - numpy==1.26.4
    - matplotlib==3.8.4
